### ISSUE TITLE
How would one center heading text in markdown.

### ISSUE THREAD

**Issue by PostalMike** [zairahira/Markdown-cheatsheet#6]
Hello,

I'm trying to center a title like this:

|| Column 2 ||
|| :---: ||
# TFS BUILD

and have tried also this:

|| Column 2 ||
|| :---: ||
|| # TFS BUILD ||

This is the way the word document that we are porting to markdown is styled.  I would like to copy the format completely so where heading text is centered, would like to center it.

Perhaps a table isn't the way to do it?

Searched for 'center' in your cheat sheet, only found the table method of centering text.

**Comment by zairahira** [comment]
In tables,  `:---:` means center aligned.
You would center align a column heading and content this way:

```
| Column 1 |
| :---: | 
| Row 1, Column 1 | 
| Row 2, Column 1 | 
| Row 3, Column 1 | 
```
Result:

| Column 1 |
| :---: | 
| Row 1, Column 1 | 
| Row 2, Column 1 | 
| Row 3, Column 1 | 

Perhaps, try using a single `|` instead of `||`?
